/*
 * End-to-end visual check: runs the real QR encoder in a browser (canvas), feeds
 * the resulting data URI into PrintDoc, renders to PDF, and exports page images.
 * Also decodes the printed QR back out of the rendered page to prove the symbol
 * survives layout and rasterisation.
 */
const fs = require('fs'), path = require('path'), vm = require('vm');
const SCRATCH = '/tmp/claude-0/-home-user-Zohoextensions/81515d70-89fa-57e6-9415-6ab46779037e/scratchpad/node_modules';
const { chromium } = require(path.join(SCRATCH, 'playwright'));
const jsQR = require(path.join(SCRATCH, 'jsqr'));
const APP = path.join(__dirname, '..', 'extension', 'app', 'js');

const sandbox = { console, module: {}, exports: {}, unescape, encodeURIComponent };
sandbox.window = sandbox; vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(APP, 'print-doc.js'), 'utf8'), sandbox);
const { PrintDoc } = sandbox;

// A realistic GST signed QR: JWS over the IRP payload.
const b64u = o => Buffer.from(JSON.stringify(o)).toString('base64url');
const IRN = 'a5c12b9f8e4d7361a0b8f2c5d9e14738bc6a0f25d13e847956ab0cd2ef419a63';
const SIGNED_QR = [
  b64u({ alg: 'RS256', typ: 'JWT' }),
  b64u({ data: JSON.stringify({
    SellerGstin: '29AAAAA0000A1Z5', BuyerGstin: '29AACCM4684P1ZN',
    DocNo: 'INV/26-27/00123', DocTyp: 'INV', DocDt: '26/08/2026',
    TotInvVal: '54942.72', ItemCnt: '70', MainHsnCode: '96190010',
    Irn: IRN, IrnDt: '2026-08-26 12:42:00' }) }),
  require('crypto').randomBytes(256).toString('base64url')
].join('.');

const base = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', 'invoice.json'), 'utf8'));
const invoice = JSON.parse(JSON.stringify(base));
invoice.line_items = [];
for (let i = 1; i <= 40; i++) {
  invoice.line_items.push({
    name: `Test Article ${i} — 24 pack`,
    description: i % 3 === 0 ? `Article No.${4910000 + i}` : '',
    hsn_or_sac: '96190010', unit: 'box', quantity: i, rate: 1243.2,
    tax_percentage: 12, item_total: +(i * 1243.2).toFixed(2)
  });
}

(async () => {
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
  const page = await browser.newPage();

  // Generate the QR with the extension's own qr.js, in a real browser.
  await page.setContent('<!doctype html><html><body></body></html>');
  await page.addScriptTag({ path: path.join(APP, 'vendor-qrcode.js') });
  await page.addScriptTag({ path: path.join(APP, 'vendor-qrcode-utf8.js') });
  await page.addScriptTag({ path: path.join(APP, 'qr.js') });
  const qr = await page.evaluate(p => QR.toDataUri(p, 150, 'L'), SIGNED_QR);
  console.log(`\nQR generated by qr.js: ${qr.modules}x${qr.modules} modules, ${qr.pixels}px raster`);

  const html = PrintDoc.build({
    invoice,
    org: { name: 'Mallikarjuna Enterprises', gst_no: '29AAAAA0000A1Z5',
           address: { address: '12-3-45 Market Road', city: 'Hyderabad', state: 'Telangana',
                      zip: '500001', country: 'India' } },
    einvoice: { irn: IRN, ackNo: '112420098765432', ackDate: '2026-08-26 12:42:00',
                signedQr: SIGNED_QR },
    qrDataUri: qr.dataUri,
    settings: { header: { showQr: true, showIrn: true, showAck: true, showGstin: true,
                          showPageNumbers: true }, qrSizePx: 150, qrEcLevel: 'L' },
    docTitle: 'Tax Invoice (e-Invoice)'
  });

  // Decode the QR back out of the laid-out page to prove print rendering is lossless.
  await page.setContent(html, { waitUntil: 'networkidle' });
  const decoded = await page.evaluate(async (src) => {
    const img = new Image(); img.src = src;
    await img.decode();
    const c = document.createElement('canvas');
    c.width = img.naturalWidth; c.height = img.naturalHeight;
    c.getContext('2d').drawImage(img, 0, 0);
    const d = c.getContext('2d').getImageData(0, 0, c.width, c.height);
    return { w: c.width, h: c.height, data: Array.from(d.data) };
  }, qr.dataUri);
  const out = jsQR(new Uint8ClampedArray(decoded.data), decoded.w, decoded.h);
  console.log(`Printed QR decodes back: ${!!out}, matches signed QR exactly: ${out && out.data === SIGNED_QR}`);

  const pdfPath = path.join(__dirname, 'preview.pdf');
  await page.pdf({ path: pdfPath, format: 'A4', printBackground: true,
                   margin: { top: '10mm', bottom: '14mm', left: '10mm', right: '10mm' } });

  // Export page images so the layout can be eyeballed.
  const viewer = await browser.newPage();
  await viewer.setViewportSize({ width: 900, height: 1200 });
  const pdfB64 = fs.readFileSync(pdfPath).toString('base64');
  await viewer.setContent('<body style="margin:0"></body>');
  // pdf.js ships ESM only; load it in-page from a blob URL and import() it.
  const pdfSrc = fs.readFileSync(path.join(SCRATCH, 'pdfjs-dist/legacy/build/pdf.mjs'), 'utf8');
  const workerSrc = fs.readFileSync(path.join(SCRATCH, 'pdfjs-dist/legacy/build/pdf.worker.mjs'), 'utf8');
  await viewer.evaluate(async ({ src, worker }) => {
    const mk = s => URL.createObjectURL(new Blob([s], { type: 'text/javascript' }));
    window.pdfjsLib = await import(mk(src));
    window.pdfjsLib.GlobalWorkerOptions.workerSrc = mk(worker);
  }, { src: pdfSrc, worker: workerSrc });

  for (const p of [1, 2]) {
    const dataUrl = await viewer.evaluate(async ({ b64, pageNo }) => {
      const lib = window.pdfjsLib;
      const bin = atob(b64), arr = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
      const doc = await lib.getDocument({ data: arr, useSystemFonts: true }).promise;
      const pg = await doc.getPage(pageNo);
      const vp = pg.getViewport({ scale: 1.6 });
      const c = document.createElement('canvas');
      c.width = vp.width; c.height = vp.height;
      await pg.render({ canvasContext: c.getContext('2d'), viewport: vp }).promise;
      return c.toDataURL('image/png');
    }, { b64: pdfB64, pageNo: p });
    fs.writeFileSync(path.join(__dirname, `preview-page${p}.png`),
                     Buffer.from(dataUrl.split(',')[1], 'base64'));
    console.log(`wrote test/preview-page${p}.png`);
  }
  await browser.close();
})();
